### ISSUE TITLE
大佬 请问下

### ISSUE THREAD

**Issue by yuxingxu** [RoadIsLong/52pojie_Sign#1]
大佬请问下cookie 的书写方式是？cookie?还是COOKIE

**Comment by HailongJson** [comment]
> 

更新了README，你可以看一下。需要在你的设置里面为仓库设置一个密钥。代码中会去读取这个密钥，密钥内容就是你抓取到的Cookie

**Comment by yuxingxu** [comment]
已解决，请问下大佬，这个可以搞成类似青龙面板登陆那种碼

**Comment by HailongJson** [comment]
> 

[青龙对应的库挺多的，你可以试下。](https://github.com/Oreomeow/checkinpanel)
我主要是因为服务器到期了没续费，就白嫖github的action单独弄了个百度贴吧签到和这个

**Comment by yuxingxu** [comment]
不是进行中的任务，这个是签到成功了吗 大佬

**Comment by RoadIsLong** [comment]
是正常的，说明今天已经签过了，你在上一条执行记录里面应该是可以看到签到成功提示的。
这是为了避免网络问题导致的签到不成功，我在定时任务里面配置的是一天执行两次，你可以自行修改

**Comment by GTian5418** [comment]
请问如何移植到云函数上运行呀
