### ISSUE TITLE
关于cookie格式问题

### ISSUE THREAD

**Issue by flowercoder** [RoadIsLong/52pojie_Sign#3]
通过getcookie.txt 和edit this cookie插件取的cookie当存入secret的值，都没跑出来
最后还是通过网页上嘴基本的F12复制到的cookie，运行成功了。
希望大侠可以之后更新一个cookie的样例，毕竟还是有很多人都希望用到这个的。

**Comment by RoadIsLong** [comment]
嗯,已经在README中写了个大致的步骤
